//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Shared__LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Shared__LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\15\DO_AN_FPT_SHOP\Views\Shared\_LayoutAdmin.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\15\DO_AN_FPT_SHOP\Views\Shared\_LayoutAdmin.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_LayoutAdmin.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_LayoutAdmin.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_LayoutAdmin.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_LayoutAdmin.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
