//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;

#line 2 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
using System.Linq;

#line default
#line hidden
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
using DO_AN_FPT_SHOP.Models;

#line default
#line hidden

#line 3 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
using DO_AN_FPT_SHOP.Controllers;

#line default
#line hidden

public class _Page__MasterLayout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__MasterLayout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 4 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 5 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                      __o = Url.Action("Search", "Products");


#line default
#line hidden

#line 6 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                  __o = Url.Action("Login", "Users");


#line default
#line hidden

#line 7 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                      
                                        var account = "Tài khoản";

                                        if (Session["Account"] != null)
                                        {
                                            account = (Session["Account"] as DO_AN_FPT_SHOP.Models.User).UserName;
                                        }
                                    

#line default
#line hidden

#line 8 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                  __o = account;


#line default
#line hidden

#line 9 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                                                                 __o = Url.Action("Login", "Users");


#line default
#line hidden

#line 10 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                                                                 __o = Url.Action("Profile", "Users");


#line default
#line hidden

#line 11 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                             __o = Url.Action("Cart", "OrderList");


#line default
#line hidden

#line 12 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                      
                                        if (Session["Account"] != null)
                                        {
                                            Session["CountCart"] = OrderListController.GetTotalQuan((Session["Account"] as User).UserName);
                                        }

                                    

#line default
#line hidden

#line 13 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                    if (Session["Account"] != null && Session["CountCart"] != null)
                                    {
                                        

#line default
#line hidden

#line 14 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                            if ((int)Session["CountCart"] != 0 && (int)Session["CountCart"] != null)
                                            {

#line default
#line hidden

#line 15 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                        __o = Html.Raw(Session["CountCart"]);


#line default
#line hidden

#line 16 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                                            }

#line default
#line hidden

#line 17 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                              
                                    }

#line default
#line hidden

#line 18 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                    __o = Url.Action("Category","Categories",new {cateid=1});


#line default
#line hidden

#line 19 "C:\Users\truon\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\13\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;

#line 2 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
using System.Linq;

#line default
#line hidden
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
using DO_AN_FPT_SHOP.Models;

#line default
#line hidden

#line 3 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
using DO_AN_FPT_SHOP.Controllers;

#line default
#line hidden

public class _Page__MasterLayout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__MasterLayout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 4 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 5 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                      __o = Url.Action("Search", "Products");


#line default
#line hidden

#line 6 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                  __o = Url.Action("Login", "Users");


#line default
#line hidden

#line 7 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                      
                                        var account = "Tài khoản";

                                        if (Session["Account"] != null)
                                        {
                                            account = (Session["Account"] as DO_AN_FPT_SHOP.Models.User).UserName;
                                        }
                                    

#line default
#line hidden

#line 8 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                  __o = account;


#line default
#line hidden

#line 9 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                                                                 __o = Url.Action("Login", "Users");


#line default
#line hidden

#line 10 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                                                                 __o = Url.Action("Profile", "Users");


#line default
#line hidden

#line 11 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                             __o = Url.Action("Cart", "OrderList");


#line default
#line hidden

#line 12 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                      
                                        if (Session["Account"] != null)
                                        {
                                            Session["CountCart"] = OrderListController.GetTotalQuan((Session["Account"] as User).UserName);
                                        }

                                    

#line default
#line hidden

#line 13 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                    if (Session["Account"] != null && Session["CountCart"] != null)
                                    {
                                        

#line default
#line hidden

#line 14 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                            if ((int)Session["CountCart"] != 0 && (int)Session["CountCart"] != null)
                                            {

#line default
#line hidden

#line 15 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                        __o = Html.Raw(Session["CountCart"]);


#line default
#line hidden

#line 16 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                                                            }

#line default
#line hidden

#line 17 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                              
                                    }

#line default
#line hidden

#line 18 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
                                    __o = Url.Action("Category","Categories",new {cateid=1});


#line default
#line hidden

#line 19 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\Shared\_MasterLayout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
