//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
using DO_AN_FPT_SHOP.Models;

#line default
#line hidden

public class _Page_Views_OrderList_ChiTietDon_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_OrderList_ChiTietDon_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
  
    ViewBag.Title = "ChiTietDon";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";


#line default
#line hidden

#line 4 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
    foreach (var orderDe in Model)
    {
        

#line default
#line hidden

#line 5 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
           __o = Html.DisplayFor(orDeItem => orderDe.OrderID);


#line default
#line hidden

#line 6 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
           __o = Html.DisplayFor(orDeItem => orderDe.OrderDetailID);


#line default
#line hidden

#line 7 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
           __o = Html.DisplayFor(orDeItem => orderDe.ProDeID);


#line default
#line hidden

#line 8 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
           __o = Html.DisplayFor(orDeItem=>orderDe.ProDetail.Product.ProName);


#line default
#line hidden

#line 9 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
                                             __o = Html.DisplayFor(orDeItem=>orderDe.ProDetail.ColorProDes.FirstOrDefault().ProImg);


#line default
#line hidden

#line 10 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
           __o = Html.DisplayFor(orDeItem => orderDe.Quantity);


#line default
#line hidden

#line 11 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
           __o = Html.DisplayFor(orDeItem => orderDe.Price);


#line default
#line hidden

#line 12 "C:\Users\ACER\AppData\Local\Temp\2C19C00D6AB0E4F1093734CCC32412FA95B3\14\DO_AN_FPT_SHOP\Views\OrderList\ChiTietDon.cshtml"
             
    }

#line default
#line hidden
}
}
}
