//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_FPT_SHOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Phone { get; set; }
        public string AdName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
    
        public virtual User User { get; set; }
    }
}
