//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_FPT_SHOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderVoucher
    {
        public int VoucherID { get; set; }
        public int OrderID { get; set; }
        public Nullable<bool> VoucherStatus { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
